baseURL = 'http://revitalizationtechnology.com/'
locale = 'en-us'
title = 'Revitalization Technology'
theme = 'hugo-hero-theme'
googleAnalytics = 'G-084817PXB0'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  google_analytics_id="G-084817PXB0"

  [params.logo]
    mobile = "images/Wordmark_Transparent_Cropped.png"
    mobile_height = "70px"
    mobile_width = "150px"
    desktop = "images/Wordmark_Transparent_Cropped.png"
    desktop_height = "70px"
    desktop_width = "150px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."

[[menu.main]]
	name = "What"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "How"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "Who"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4